query getHomePageSocialPosts($filter: GenericFilterRequestSocialPostReqType!){
    getHomePageSocialPosts(filter: $filter) {
    listDto {
      items {
        id
        body
        ownerUserId
        audience
        status
        isDeleted
        location
        tagIds
        mentionedUserIds
        videoUrls
        pictureUrls
        createdDateTime
        firstName
        fullName
        lastName
        userName
        userAvatarUrl
        countOfComments
        countOfLikes
        countOfShared
        countOfViews
        placeId
        placeMainText
        placeDescription
        placeSecondaryText
      }
      count
    }
  }
}
