query getUserWebSites($filter: GenericFilterRequestUserWebSiteGetAllInputType!) {
  getUserWebSites(filter: $filter) {
    listDto {
      items {
        id
        userId
        webSiteUrl
        audience
      }
    }
  }
}
