
query getUserSocialMedias($filter: GenericFilterRequestUserSocialMediaGetAllInputType!){
  getUserSocialMedias(filter: $filter){
    listDto{
      items {
       id
        userName
        userId
        audience
        socialMediaDto{
          id
          title
        }
      }
    }
  }
}