query getPersonColleges($filter: GenericFilterRequestPersonCollegeGetAllInputType!) {
  getPersonColleges(filter: $filter) {
    listDto {
      items {
        id
        collegeDto {
          id
          name
          country
        }
        concentrationDto {
          id
          title
        }
        graduated
        startDate
        endDate
        audience
        instituteType
      }
    }
  }
}
