query getExperiences($filter:GenericFilterRequestPersonExperienceInputType!){
  getExpriences(filter:$filter) {
    listDto {
      items {
        title
        id
        description
        employmentType
        audience
        startDate
        endDate
        stillWorkingThere
        companyId
        companyDto {
          id
          title
          logoUrl
        }
        cityDto{
          id
          name
          placeId
        }
        cityId
        mediaUrl
      } 
    }
  }
}