query searchCompanies($filter: GenericFilterRequestCompanySearchInputType! ){
  searchCompanies(filter: $filter) {
    listDto {
      items {
        id
        title
        logoUrl
      }
    }
  }
}