query searchCertificateNames($filter:GenericFilterRequestCertificateNameSearchInputType!){
  searchCertificateNames(filter:$filter){
    listDto{
      items{
        id
        title
      }
    }
  }
}