query searchIssuingOrganizations($filter:GenericFilterRequestIssuingOrganizationSearchInputType!){
  searchIssuingOrganizations(filter:$filter){
    listDto{
      items{
        id
        title
      }
    }
  }
}